name: Supabase PDF Workflow

on:
  schedule:
    - cron: '0 4 * * *' # Täglich um 02:00 UTC (anpassen falls nötig)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Workflow ausführen
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: node src/index.js
