name: Generate and Send Reports Workflow

on:
  schedule:
    - cron: '22 4 28 * *'  # Anpassen: L채uft am 28. jeden Monats um 04:22 UTC (oder t채glich, falls gew체nscht)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Abh채ngigkeiten installieren
        run: npm install

      - name: Run Generate and Send Reports Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: node src/generate_and_send_reports.js
