name: Update Freizeitkonto Workflow

on:
  schedule:
    - cron: '12 0 01 * *'  # Läuft täglich um 02:00 UTC (anpassen falls nötig)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Run Update Freizeitkonto Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: node src/update_freizeitkonto.js
